on: [push]

jobs:
    deploy_job:
    runs-on: ubuntu-latest
    name: deployfiles
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      - name: Deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.USERNAME }}
        server: ${{ secrets.SERVER }}
        port: ${{ secrets.PORT }}
        local_path: './static/*'
        remote_path: '/var/www/app'
        sftp_only: true
        password: ${{ secrets.PASSWORD }}
            
        