name: Deploy Files

on:
  push:
    branches:
      - deploy
  # Enables manually triggering of Workflow with file synchronization option
  # workflow_dispatch:
  #   inputs:
  #     sync:
  #       description: "File synchronization"
  #       required: true
  #       default: "delta"

jobs:
  deploy-master:
    name: "deploy branch"
    if: ${{ github.ref == 'refs/heads/deploy' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{secrets.SERVER}}
          remote-user: ${{secrets.USERNAME}}
          remote-port: ${{secrets.PORT}}
          remote-password: ${{ secrets.PASSWORD }}
          remote-path: "/home/container"
          sync: delta